# Generated by Django 5.1.3 on 2024-12-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='photo',
        ),
    ]
