# Generated by Django 5.1.3 on 2024-12-25 10:35

from django.db import migrations, models

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_menuitem_category_remove_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='No description available', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
